/*
  מוסר — corpus de frases.

  Cada frase lleva su fuente cuando la tiene (pasuk, Pirkei Avot, Guemará o un
  sefer de musar), su TEMA y su TONO. El tono respeta la exigencia del sistema:
   - gentle    → se muestra en cualquier nivel
   - firm      → se muestra en 'firm' y 'demanding'
   - demanding → solo en 'demanding'

  Verbatim en hebreo solo donde el texto original ES hebreo y es de cita segura
  (Tanaj, Mishná, Guemará). Las líneas de los seforim de musar son la ENSEÑANZA
  del lugar citado, redactada en castellano — no una cita literal — y por eso van
  sin `he`.

  Las frases con `mine: true` serían frases propias que cada usuario podría añadir.
*/

export type MusarTheme = 'prioridad' | 'exigencia' | 'teshuva' | 'zman' | 'simja' | 'anava';
export type MusarTone = 'gentle' | 'firm' | 'demanding';

export interface MusarLine {
  id: string;
  he?: string;
  es: string;
  /** Fuente en hebreo, si aplica ("מִשְׁלֵי ג׳ ו׳", "מְסִלַּת יְשָׁרִים"). */
  source?: string;
  /** Fuente en caracteres latinos ("Mishlé 3:6", "Mesilat Yesharim, cap. 1"). */
  sourceEs?: string;
  theme: MusarTheme;
  tone: MusarTone;
  /** Escrito por el usuario. */
  mine?: boolean;
}

export const MUSAR_THEMES: Record<
  MusarTheme,
  { he: string; es: string; desc: string; mekor: string; mekorEs: string }
> = {
  prioridad: {
    he: 'ה׳ בָּרֹאשׁ',
    es: 'Hashem primero',
    desc: 'Ponerlo a Él antes que a todo lo demás: antes del dinero, del qué dirán, de la comodidad y de los planes propios.',
    mekor: '«בְּכָל דְּרָכֶיךָ דָעֵהוּ»',
    mekorEs: 'Mishlé 3:6 — «En todos tus caminos conócelo.»',
  },
  exigencia: {
    he: 'זְרִיזוּת',
    es: 'Exigencia y prisa',
    desc: 'No aflojar, no posponer, no conformarse con lo cómodo. El estándar sube, no baja; hoy es corto y la obra es mucha.',
    mekor: '«הַיּוֹם קָצָר וְהַמְּלָאכָה מְרֻבָּה»',
    mekorEs: 'Pirkei Avot 2:15 — «El día es corto y la obra, mucha.»',
  },
  teshuva: {
    he: 'תְּשׁוּבָה',
    es: 'El regreso',
    desc: 'La caída se responde volviendo, ahora, sin hundirse en la culpa. Siete veces cae el justo y se levanta.',
    mekor: '«שֶׁבַע יִפּוֹל צַדִּיק וָקָם»',
    mekorEs: 'Mishlé 24:16 — «Siete veces cae el justo y se levanta.»',
  },
  zman: {
    he: 'הַזְּמַן',
    es: 'El tiempo y el fin',
    desc: 'La vida tiene fecha de entrega. Lo que hoy parece eterno mañana es polvo; los años no son propiedad, son responsabilidad.',
    mekor: '«לִמְנוֹת יָמֵינוּ כֵּן הוֹדַע»',
    mekorEs: 'Tehilim 90:12 — «Enséñanos a contar nuestros días.»',
  },
  simja: {
    he: 'שִׂמְחָה',
    es: 'Alegría en la avodá',
    desc: 'Servir con gusto, no con cara larga. La amargura tranca la puerta; la alegría la abre. Rico es el que está contento con lo suyo.',
    mekor: '«עִבְדוּ אֶת ה׳ בְּשִׂמְחָה»',
    mekorEs: 'Tehilim 100:2 — «Sirvan a Hashem con alegría.»',
  },
  anava: {
    he: 'עֲנָוָה',
    es: 'Humildad y no seguir a la masa',
    desc: 'No medirte por los demás ni correr adonde corren todos. Mirar cuánto te falta a ti, y caminar discreto con Él.',
    mekor: '«לֹא תִהְיֶה אַחֲרֵי רַבִּים לְרָעֹת»',
    mekorEs: 'Shemot 23:2 — «No sigas a la mayoría para el mal.»',
  },
};

export const MUSAR: MusarLine[] = [
  // ─────────────────────────────── פסוקים ───────────────────────────────
  {
    id: 'p-mishle-3-6',
    he: 'בְּכָל דְּרָכֶיךָ דָעֵהוּ וְהוּא יְיַשֵּׁר אֹרְחֹתֶיךָ',
    es: 'En todos tus caminos conócelo, y Él enderezará tus sendas.',
    source: 'מִשְׁלֵי ג׳:ו׳',
    sourceEs: 'Mishlé 3:6',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-16-8',
    he: 'שִׁוִּיתִי ה׳ לְנֶגְדִּי תָמִיד',
    es: 'Tengo presente a Hashem delante de mí, siempre.',
    source: 'תְּהִלִּים ט״ז:ח׳',
    sourceEs: 'Tehilim 16:8',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-90-12',
    he: 'לִמְנוֹת יָמֵינוּ כֵּן הוֹדַע וְנָבִא לְבַב חָכְמָה',
    es: 'Enséñanos a contar nuestros días, para que traigamos un corazón sabio.',
    source: 'תְּהִלִּים צ׳:י״ב',
    sourceEs: 'Tehilim 90:12',
    theme: 'zman',
    tone: 'firm',
  },
  {
    id: 'p-tehilim-100-2',
    he: 'עִבְדוּ אֶת ה׳ בְּשִׂמְחָה בֹּאוּ לְפָנָיו בִּרְנָנָה',
    es: 'Sirvan a Hashem con alegría, vengan ante Él con canto.',
    source: 'תְּהִלִּים ק׳:ב׳',
    sourceEs: 'Tehilim 100:2',
    theme: 'simja',
    tone: 'gentle',
  },
  {
    id: 'p-mishle-24-16',
    he: 'כִּי שֶׁבַע יִפּוֹל צַדִּיק וָקָם',
    es: 'Porque siete veces cae el justo, y se levanta.',
    source: 'מִשְׁלֵי כ״ד:ט״ז',
    sourceEs: 'Mishlé 24:16',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'p-shemot-23-2',
    he: 'לֹא תִהְיֶה אַחֲרֵי רַבִּים לְרָעֹת',
    es: 'No sigas a la mayoría para el mal.',
    source: 'שְׁמוֹת כ״ג:ב׳',
    sourceEs: 'Shemot 23:2',
    theme: 'anava',
    tone: 'firm',
  },
  {
    id: 'p-devarim-30-19',
    he: 'וּבָחַרְתָּ בַּחַיִּים לְמַעַן תִּחְיֶה אַתָּה וְזַרְעֶךָ',
    es: 'Y elegirás la vida, para que vivas tú y tu descendencia.',
    source: 'דְּבָרִים ל׳:י״ט',
    sourceEs: 'Devarim 30:19',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'p-kohelet-12-13',
    he: 'סוֹף דָּבָר הַכֹּל נִשְׁמָע אֶת הָאֱלֹהִים יְרָא וְאֶת מִצְוֹתָיו שְׁמוֹר כִּי זֶה כָּל הָאָדָם',
    es: 'Fin del asunto, todo escuchado: teme a Dios y guarda Sus mitzvot, porque esto es todo el hombre.',
    source: 'קֹהֶלֶת י״ב:י״ג',
    sourceEs: 'Kohelet 12:13',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'p-micha-6-8',
    he: 'הִגִּיד לְךָ אָדָם מַה טּוֹב וּמָה ה׳ דּוֹרֵשׁ מִמְּךָ כִּי אִם עֲשׂוֹת מִשְׁפָּט וְאַהֲבַת חֶסֶד וְהַצְנֵעַ לֶכֶת עִם אֱלֹהֶיךָ',
    es: 'Se te ha dicho, hombre, qué es bueno: hacer justicia, amar la bondad y caminar discretamente con tu Dios.',
    source: 'מִיכָה ו׳:ח׳',
    sourceEs: 'Michá 6:8',
    theme: 'anava',
    tone: 'gentle',
  },
  {
    id: 'p-yirmiya-9-23',
    he: 'כִּי אִם בְּזֹאת יִתְהַלֵּל הַמִּתְהַלֵּל הַשְׂכֵּל וְיָדֹעַ אוֹתִי',
    es: 'Que el que se enorgullece se enorgullezca solo de esto: de entender y conocerme a Mí.',
    source: 'יִרְמְיָהוּ ט׳:כ״ג',
    sourceEs: 'Yirmiyahu 9:23',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'p-tehilim-37-5',
    he: 'גּוֹל עַל ה׳ דַּרְכֶּךָ וּבְטַח עָלָיו וְהוּא יַעֲשֶׂה',
    es: 'Encomienda a Hashem tu camino, confía en Él, y Él actuará.',
    source: 'תְּהִלִּים ל״ז:ה׳',
    sourceEs: 'Tehilim 37:5',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-27-4',
    he: 'אַחַת שָׁאַלְתִּי מֵאֵת ה׳ אוֹתָהּ אֲבַקֵּשׁ שִׁבְתִּי בְּבֵית ה׳ כָּל יְמֵי חַיַּי',
    es: 'Una cosa pedí a Hashem, eso buscaré: habitar en la casa de Hashem todos los días de mi vida.',
    source: 'תְּהִלִּים כ״ז:ד׳',
    sourceEs: 'Tehilim 27:4',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-eicha-3-40',
    he: 'נַחְפְּשָׂה דְרָכֵינוּ וְנַחְקֹרָה וְנָשׁוּבָה עַד ה׳',
    es: 'Examinemos nuestros caminos, investiguémoslos, y volvamos hasta Hashem.',
    source: 'אֵיכָה ג׳:מ׳',
    sourceEs: 'Eijá 3:40',
    theme: 'teshuva',
    tone: 'firm',
  },
  {
    id: 'p-malachi-3-7',
    he: 'שׁוּבוּ אֵלַי וְאָשׁוּבָה אֲלֵיכֶם',
    es: 'Vuelvan a Mí, y Yo volveré a ustedes.',
    source: 'מַלְאָכִי ג׳:ז׳',
    sourceEs: 'Malají 3:7',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-73-25',
    he: 'מִי לִי בַשָּׁמָיִם וְעִמְּךָ לֹא חָפַצְתִּי בָאָרֶץ',
    es: '¿A quién tengo en el cielo? Y contigo, nada deseo en la tierra.',
    source: 'תְּהִלִּים ע״ג:כ״ה',
    sourceEs: 'Tehilim 73:25',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'p-mishle-3-5',
    he: 'בְּטַח אֶל ה׳ בְּכָל לִבֶּךָ וְאֶל בִּינָתְךָ אַל תִּשָּׁעֵן',
    es: 'Confía en Hashem con todo tu corazón, y no te apoyes en tu propio entendimiento.',
    source: 'מִשְׁלֵי ג׳:ה׳',
    sourceEs: 'Mishlé 3:5',
    theme: 'prioridad',
    tone: 'gentle',
  },

  // ─────────────────────────── פרקי אבות ומשנה ──────────────────────────
  {
    id: 'a-1-14',
    he: 'אִם אֵין אֲנִי לִי מִי לִי וּכְשֶׁאֲנִי לְעַצְמִי מָה אֲנִי וְאִם לֹא עַכְשָׁיו אֵימָתָי',
    es: 'Si yo no soy para mí, ¿quién lo será? Y si solo soy para mí, ¿qué soy? Y si no es ahora, ¿cuándo?',
    source: 'אָבוֹת א׳:י״ד',
    sourceEs: 'Pirkei Avot 1:14 (Hilel)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'a-2-4',
    he: 'עֲשֵׂה רְצוֹנוֹ כִּרְצוֹנְךָ בַּטֵּל רְצוֹנְךָ מִפְּנֵי רְצוֹנוֹ',
    es: 'Haz Su voluntad como si fuera la tuya; anula tu voluntad ante la Suya.',
    source: 'אָבוֹת ב׳:ד׳',
    sourceEs: 'Pirkei Avot 2:4',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'a-2-5',
    he: 'וְאַל תֹּאמַר לִכְשֶׁאִפָּנֶה אֶשְׁנֶה שֶׁמָּא לֹא תִפָּנֶה',
    es: 'No digas «cuando tenga tiempo estudiaré»: quizá no tengas tiempo.',
    source: 'אָבוֹת ב׳:ה׳',
    sourceEs: 'Pirkei Avot 2:5 (Hilel)',
    theme: 'exigencia',
    tone: 'demanding',
  },
  {
    id: 'a-2-15',
    he: 'הַיּוֹם קָצָר וְהַמְּלָאכָה מְרֻבָּה וְהַפּוֹעֲלִים עֲצֵלִים',
    es: 'El día es corto, la obra es mucha, y los obreros son perezosos.',
    source: 'אָבוֹת ב׳:ט״ו',
    sourceEs: 'Pirkei Avot 2:15 (Rabí Tarfón)',
    theme: 'exigencia',
    tone: 'demanding',
  },
  {
    id: 'a-2-16',
    he: 'לֹא עָלֶיךָ הַמְּלָאכָה לִגְמֹר וְלֹא אַתָּה בֶן חוֹרִין לִבָּטֵל מִמֶּנָּה',
    es: 'No es tuya la tarea de terminarla, pero tampoco eres libre de abandonarla.',
    source: 'אָבוֹת ב׳:ט״ז',
    sourceEs: 'Pirkei Avot 2:16 (Rabí Tarfón)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'a-3-1',
    he: 'דַּע מֵאַיִן בָּאתָ וּלְאָן אַתָּה הוֹלֵךְ וְלִפְנֵי מִי אַתָּה עָתִיד לִתֵּן דִּין וְחֶשְׁבּוֹן',
    es: 'Sabe de dónde viniste, adónde vas, y ante Quién habrás de dar cuenta y balance.',
    source: 'אָבוֹת ג׳:א׳',
    sourceEs: 'Pirkei Avot 3:1 (Akavia ben Mahalalel)',
    theme: 'zman',
    tone: 'firm',
  },
  {
    id: 'a-4-1-ashir',
    he: 'אֵיזֶהוּ עָשִׁיר הַשָּׂמֵחַ בְּחֶלְקוֹ',
    es: '¿Quién es rico? El que está contento con lo suyo.',
    source: 'אָבוֹת ד׳:א׳',
    sourceEs: 'Pirkei Avot 4:1 (Ben Zoma)',
    theme: 'simja',
    tone: 'gentle',
  },
  {
    id: 'a-4-1-gibor',
    he: 'אֵיזֶהוּ גִבּוֹר הַכּוֹבֵשׁ אֶת יִצְרוֹ',
    es: '¿Quién es fuerte? El que domina su instinto.',
    source: 'אָבוֹת ד׳:א׳',
    sourceEs: 'Pirkei Avot 4:1 (Ben Zoma)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'a-4-17',
    he: 'יָפָה שָׁעָה אַחַת בִּתְשׁוּבָה וּמַעֲשִׂים טוֹבִים בָּעוֹלָם הַזֶּה מִכָּל חַיֵּי הָעוֹלָם הַבָּא',
    es: 'Vale más una hora de teshuvá y buenas obras en este mundo que toda la vida del Mundo Venidero.',
    source: 'אָבוֹת ד׳:י״ז',
    sourceEs: 'Pirkei Avot 4:17 (Rabí Yaakov)',
    theme: 'teshuva',
    tone: 'firm',
  },
  {
    id: 'a-4-22',
    he: 'עַל כָּרְחֲךָ אַתָּה חַי וְעַל כָּרְחֲךָ אַתָּה עָתִיד לִתֵּן דִּין וְחֶשְׁבּוֹן',
    es: 'Sin que dependa de ti vives, y sin que dependa de ti habrás de dar cuenta y balance.',
    source: 'אָבוֹת ד׳:כ״ב',
    sourceEs: 'Pirkei Avot 4:22',
    theme: 'zman',
    tone: 'demanding',
  },
  {
    id: 'a-5-20',
    he: 'הֱוֵי עַז כַּנָּמֵר וְקַל כַּנֶּשֶׁר רָץ כַּצְּבִי וְגִבּוֹר כָּאֲרִי לַעֲשׂוֹת רְצוֹן אָבִיךָ שֶׁבַּשָּׁמָיִם',
    es: 'Sé audaz como el leopardo, ligero como el águila, veloz como el ciervo y fuerte como el león para hacer la voluntad de tu Padre en el Cielo.',
    source: 'אָבוֹת ה׳:כ׳',
    sourceEs: 'Pirkei Avot 5:20 (Yehudá ben Tema)',
    theme: 'exigencia',
    tone: 'demanding',
  },
  {
    id: 'a-1-15',
    he: 'עֲשֵׂה תוֹרָתְךָ קֶבַע אֱמֹר מְעַט וַעֲשֵׂה הַרְבֵּה',
    es: 'Haz de tu Torá algo fijo; di poco y haz mucho.',
    source: 'אָבוֹת א׳:ט״ו',
    sourceEs: 'Pirkei Avot 1:15 (Shamai)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'a-2-21',
    he: 'לֹא עָלֶיךָ הַמְּלָאכָה לִגְמֹר',
    es: 'Si estudiaste mucha Torá, te dan mucha recompensa; y fiel es el Patrón de tu trabajo.',
    source: 'אָבוֹת ב׳:ט״ז',
    sourceEs: 'Pirkei Avot 2:16 (Rabí Tarfón)',
    theme: 'simja',
    tone: 'gentle',
  },
  {
    id: 'a-3-15',
    he: 'הַכֹּל צָפוּי וְהָרְשׁוּת נְתוּנָה',
    es: 'Todo está previsto, y la libertad de elegir está dada.',
    source: 'אָבוֹת ג׳:ט״ו',
    sourceEs: 'Pirkei Avot 3:15 (Rabí Akiva)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'a-1-3',
    he: 'אַל תִּהְיוּ כַּעֲבָדִים הַמְשַׁמְּשִׁין אֶת הָרַב עַל מְנָת לְקַבֵּל פְּרָס',
    es: 'No sean como los sirvientes que atienden al patrón para recibir premio; sean como los que sirven sin condición.',
    source: 'אָבוֹת א׳:ג׳',
    sourceEs: 'Pirkei Avot 1:3 (Antígono de Sojó)',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'a-6-2',
    he: 'אֵין לְךָ בֶן חוֹרִין אֶלָּא מִי שֶׁעוֹסֵק בְּתַלְמוּד תּוֹרָה',
    es: 'No hay hombre libre sino el que se ocupa en el estudio de la Torá.',
    source: 'אָבוֹת ו׳:ב׳',
    sourceEs: 'Pirkei Avot 6:2',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'a-4-2',
    he: 'הֱוֵי רָץ לְמִצְוָה קַלָּה וּבוֹרֵחַ מִן הָעֲבֵרָה',
    es: 'Corre hacia la mitzvá más pequeña y huye de la falta.',
    source: 'אָבוֹת ד׳:ב׳',
    sourceEs: 'Pirkei Avot 4:2 (Ben Azai)',
    theme: 'exigencia',
    tone: 'firm',
  },

  // ─────────────────────────────── גמרא ───────────────────────────────
  {
    id: 'g-berachot-17a',
    he: 'אֶחָד הַמַּרְבֶּה וְאֶחָד הַמַּמְעִיט וּבִלְבַד שֶׁיְּכַוֵּן לִבּוֹ לַשָּׁמַיִם',
    es: 'Tanto el que hace mucho como el que hace poco, con tal de que dirija su corazón al Cielo.',
    source: 'בְּרָכוֹת י״ז.',
    sourceEs: 'Berajot 17a',
    theme: 'simja',
    tone: 'gentle',
  },
  {
    id: 'g-shabbat-104a',
    he: 'הַבָּא לִטַּהֵר מְסַיְּעִין אוֹתוֹ',
    es: 'Al que viene a purificarse, lo ayudan desde el Cielo.',
    source: 'שַׁבָּת ק״ד.',
    sourceEs: 'Shabat 104a',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'g-eruvin-13b',
    he: 'עַכְשָׁיו שֶׁנִּבְרָא יְפַשְׁפֵּשׁ בְּמַעֲשָׂיו',
    es: 'Ya que el hombre fue creado, que revise sus actos.',
    source: 'עֵרוּבִין י״ג:',
    sourceEs: 'Eruvin 13b',
    theme: 'exigencia',
    tone: 'demanding',
  },
  {
    id: 'g-sanhedrin-37a',
    he: 'חַיָּב אָדָם לוֹמַר בִּשְׁבִילִי נִבְרָא הָעוֹלָם',
    es: 'Cada persona está obligada a decir: «Por mí fue creado el mundo.»',
    source: 'סַנְהֶדְרִין ל״ז.',
    sourceEs: 'Sanhedrín 37a',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'g-tamid-32a',
    he: 'אֵיזֶהוּ חָכָם הָרוֹאֶה אֶת הַנּוֹלָד',
    es: '¿Quién es sabio? El que ve lo que va a nacer de sus actos.',
    source: 'תָּמִיד ל״ב.',
    sourceEs: 'Tamid 32a',
    theme: 'zman',
    tone: 'firm',
  },
  {
    id: 'g-kiddushin-40b',
    he: 'לְעוֹלָם יִרְאֶה אָדָם עַצְמוֹ כְּאִלּוּ חֶצְיוֹ חַיָּב וְחֶצְיוֹ זַכַּאי',
    es: 'Que la persona se vea siempre como si estuviera mitad culpable y mitad inocente: una sola acción inclina la balanza.',
    source: 'קִדּוּשִׁין מ׳:',
    sourceEs: 'Kidushín 40b',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'g-avodazara-19a',
    he: 'לְעוֹלָם יִלְמַד אָדָם תּוֹרָה בְּמָקוֹם שֶׁלִּבּוֹ חָפֵץ',
    es: 'Que la persona estudie Torá en el tema que su corazón desea.',
    source: 'עֲבוֹדָה זָרָה י״ט.',
    sourceEs: 'Avodá Zará 19a',
    theme: 'simja',
    tone: 'gentle',
  },
  {
    id: 'g-menachot-99b',
    he: 'אֵין הַתּוֹרָה מִתְקַיֶּמֶת אֶלָּא בְּמִי שֶׁמֵּמִית עַצְמוֹ עָלֶיהָ',
    es: 'La Torá solo perdura en quien se entrega a ella hasta el límite de sus fuerzas.',
    source: 'בְּרָכוֹת ס״ג:',
    sourceEs: 'Berajot 63b',
    theme: 'exigencia',
    tone: 'demanding',
  },

  // ───────────────────── ספרי מוסר (enseñanza + fuente) ─────────────────────
  {
    id: 'm-mesilat-1',
    es: 'El hombre fue creado solo para deleitarse en Hashem; todo lo demás de este mundo es medio, no fin.',
    source: 'מְסִלַּת יְשָׁרִים א׳',
    sourceEs: 'Mesilat Yesharim, cap. 1 (Ramjal)',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'm-mesilat-intro',
    es: 'Lo más sabido es lo más olvidado: por evidente no se piensa, y por no pensarse no se cumple.',
    source: 'מְסִלַּת יְשָׁרִים, הַקְדָּמָה',
    sourceEs: 'Mesilat Yesharim, introducción',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'm-mesilat-zehirut',
    es: 'Vive revisando tus caminos como un comerciante revisa sus cuentas, para no descubrir tarde que estabas en pérdida.',
    source: 'מְסִלַּת יְשָׁרִים ג׳',
    sourceEs: 'Mesilat Yesharim, cap. 3 (Zehirut)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'm-mesilat-zerizut',
    es: 'La pereza rara vez dice «no»; dice «más tarde». Y más tarde no llega.',
    source: 'מְסִלַּת יְשָׁרִים ו׳-ז׳',
    sourceEs: 'Mesilat Yesharim, cap. 6–7 (Zerizut)',
    theme: 'exigencia',
    tone: 'demanding',
  },
  {
    id: 'm-mesilat-zerizut-2',
    es: 'La misma prisa con que te mueves por lo que te importa de verdad, ponla en la avodá.',
    source: 'מְסִלַּת יְשָׁרִים ז׳',
    sourceEs: 'Mesilat Yesharim, cap. 7 (Zerizut)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'm-chovot-cheshbon',
    es: 'Hazle cuentas a tu alma hoy, mientras puedes corregir, y no dejes la deuda para cuando ya no haya con qué pagarla.',
    source: 'חוֹבוֹת הַלְּבָבוֹת, שַׁעַר חֶשְׁבּוֹן הַנֶּפֶשׁ',
    sourceEs: 'Jovot HaLevavot, Portal del Cheshbon HaNefesh',
    theme: 'exigencia',
    tone: 'demanding',
  },
  {
    id: 'm-chovot-bitachon',
    es: 'Quien confía en Hashem descansa de mil preocupaciones que los demás cargan sin necesidad.',
    source: 'חוֹבוֹת הַלְּבָבוֹת, שַׁעַר הַבִּטָּחוֹן',
    sourceEs: 'Jovot HaLevavot, Portal del Bitajón',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'm-chovot-avoda',
    es: 'Antes de cada acto, pregúntate para quién lo haces; el corazón se desvía sin avisar.',
    source: 'חוֹבוֹת הַלְּבָבוֹת, שַׁעַר יִחוּד הַמַּעֲשֶׂה',
    sourceEs: 'Jovot HaLevavot, Portal de la sinceridad del acto',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'm-orchot-simcha',
    es: 'La tristeza tranca la puerta de la avodá; la alegría la abre de par en par.',
    source: 'אָרְחוֹת צַדִּיקִים, שַׁעַר הַשִּׂמְחָה',
    sourceEs: 'Orjot Tzadikim, Portal de la Alegría',
    theme: 'simja',
    tone: 'gentle',
  },
  {
    id: 'm-orchot-anava',
    es: 'El humilde no se compara con nadie: solo mide cuánto le falta todavía a él.',
    source: 'אָרְחוֹת צַדִּיקִים, שַׁעַר הָעֲנָוָה',
    sourceEs: 'Orjot Tzadikim, Portal de la Humildad',
    theme: 'anava',
    tone: 'gentle',
  },
  {
    id: 'm-orchot-zerizut',
    es: 'El perezoso siempre tiene una razón para empezar mañana; el diligente empieza con la razón en contra.',
    source: 'אָרְחוֹת צַדִּיקִים, שַׁעַר הַזְּרִיזוּת',
    sourceEs: 'Orjot Tzadikim, Portal de la Diligencia',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'm-rambam-teshuva-2-1',
    es: 'La teshuvá completa es volver a la misma prueba, con la misma fuerza, y esta vez no caer.',
    source: 'רַמְבַּ״ם, הִלְכוֹת תְּשׁוּבָה ב׳:א׳',
    sourceEs: 'Rambam, Hiljot Teshuvá 2:1',
    theme: 'teshuva',
    tone: 'firm',
  },
  {
    id: 'm-rambam-teshuva-3-4',
    es: 'Vive el día como si el mundo entero estuviera en equilibrio y tu próxima acción lo inclinara entero.',
    source: 'רַמְבַּ״ם, הִלְכוֹת תְּשׁוּבָה ג׳:ד׳',
    sourceEs: 'Rambam, Hiljot Teshuvá 3:4',
    theme: 'exigencia',
    tone: 'demanding',
  },
  {
    id: 'm-rambam-deot-3-3',
    es: 'Que tu comer, tu dormir y tu trabajo sean para tener un cuerpo con el cual servir a Hashem.',
    source: 'רַמְבַּ״ם, הִלְכוֹת דֵּעוֹת ג׳:ג׳',
    sourceEs: 'Rambam, Hiljot Deot 3:3',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'm-gra-even',
    es: 'Toda la avodá del hombre es quebrar la midá que aún no venció; si no la trabaja, ¿para qué vive?',
    source: 'הַגְרָ״א, אֶבֶן שְׁלֵמָה',
    sourceEs: 'El Gaón de Vilna, Even Shleimá',
    theme: 'exigencia',
    tone: 'demanding',
  },
  {
    id: 'm-salanter-material',
    es: 'El carácter del que uno está hecho pide trabajo diario, igual que el cuerpo pide pan.',
    source: 'ר׳ יִשְׂרָאֵל סָלַנְטֶר',
    sourceEs: 'Rabí Israel Salanter',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'm-salanter-vela',
    es: 'Mientras la vela sigue encendida, todavía se puede arreglar.',
    source: 'ר׳ יִשְׂרָאֵל סָלַנְטֶר',
    sourceEs: 'Rabí Israel Salanter',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'm-dessler-bechira',
    es: 'La lucha real está solo en un punto: donde hoy dudas. Ni más arriba ni más abajo. Ahí se gana o se pierde el día.',
    source: 'מִכְתָּב מֵאֵלִיָּהוּ, נְקֻדַּת הַבְּחִירָה',
    sourceEs: 'Mijtav MeEliyahu, «el punto de elección» (Rav Dessler)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'm-besht-machshava',
    es: 'Donde está el pensamiento del hombre, ahí está él entero.',
    source: 'הַבַּעַל שֵׁם טוֹב',
    sourceEs: 'El Baal Shem Tov',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'm-nachman-yeush',
    he: 'אָסוּר לְהִתְיָאֵשׁ',
    es: 'Está prohibido rendirse.',
    source: 'ר׳ נַחְמָן מִבְּרֶסְלֶב',
    sourceEs: 'Rabí Najman de Breslov',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'm-nachman-gesher',
    he: 'כָּל הָעוֹלָם כֻּלּוֹ גֶּשֶׁר צַר מְאֹד וְהָעִקָּר לֹא לְפַחֵד כְּלָל',
    es: 'Todo el mundo es un puente muy angosto, y lo esencial es no tener miedo en absoluto.',
    source: 'מְיֻחָס לְר׳ נַחְמָן מִבְּרֶסְלֶב',
    sourceEs: 'Atribuido a Rabí Najman de Breslov',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'm-nachman-tikun',
    es: 'Si crees que se puede dañar, cree que se puede reparar.',
    source: 'ר׳ נַחְמָן מִבְּרֶסְלֶב',
    sourceEs: 'Rabí Najman de Breslov',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'm-chazon-ish',
    es: 'Quien vive con la pregunta «¿qué se espera de mí ahora?» no se pierde.',
    source: 'הֶחָזוֹן אִישׁ',
    sourceEs: 'El Jazón Ish',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'm-tanya-benoni',
    es: 'No se te pide no sentir el tirón; se te pide no dejar que gobierne tu mano, tu boca ni tu mente.',
    source: 'תַּנְיָא, פֶּרֶק י״ב',
    sourceEs: 'Tania, cap. 12 (el benoní)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'm-cheshbon-hanefesh',
    es: 'Una falta repetida deja de sentirse como falta; por eso hay que nombrarla en voz alta cada noche.',
    source: 'חֶשְׁבּוֹן הַנֶּפֶשׁ (ר׳ מְנַחֵם מֶנְדְּל לֶפִין)',
    sourceEs: 'Cheshbon HaNefesh (R. Menajem Mendel Lefin)',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'm-shaarei-teshuva',
    es: 'La demora en volver es, en sí misma, otra falta que se suma cada día que pasa.',
    source: 'שַׁעֲרֵי תְּשׁוּבָה, שַׁעַר א׳',
    sourceEs: 'Shaarei Teshuvá, Portal 1 (Rabenu Yoná)',
    theme: 'teshuva',
    tone: 'demanding',
  },
  {
    id: 'm-shaarei-teshuva-2',
    es: 'Después de la caída, lo que define a la persona no es el tropiezo sino la velocidad con que se levanta.',
    source: 'שַׁעֲרֵי תְּשׁוּבָה, שַׁעַר א׳',
    sourceEs: 'Shaarei Teshuvá, Portal 1 (Rabenu Yoná)',
    theme: 'teshuva',
    tone: 'firm',
  },
  {
    id: 'm-duties-time',
    es: 'Tus días son cartas que estás escribiendo; un día alguien las va a leer todas juntas.',
    source: 'עַל פִּי חוֹבוֹת הַלְּבָבוֹת',
    sourceEs: 'Según Jovot HaLevavot, Portal del Cheshbon HaNefesh',
    theme: 'zman',
    tone: 'firm',
  },
  {
    id: 'm-orchot-kaas',
    es: 'El que se enoja, es como si sirviera a otro dios: por un momento, Hashem dejó de ser lo primero.',
    source: 'אָרְחוֹת צַדִּיקִים, שַׁעַר הַכַּעַס',
    sourceEs: 'Orjot Tzadikim, Portal de la Ira',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'm-mesilat-worldly',
    es: 'Las comodidades de este mundo no son el pago del trabajo; son la herramienta. Confundirlas es perder el sueldo.',
    source: 'מְסִלַּת יְשָׁרִים א׳',
    sourceEs: 'Mesilat Yesharim, cap. 1 (Ramjal)',
    theme: 'zman',
    tone: 'firm',
  },
  {
    id: 'm-anava-crowd',
    es: 'Que muchos hagan algo no lo vuelve verdad; solo lo vuelve común.',
    source: 'עַל פִּי אָרְחוֹת צַדִּיקִים',
    sourceEs: 'Según Orjot Tzadikim, Portal de la Humildad',
    theme: 'anava',
    tone: 'firm',
  },

  // ────────────── פסוקים — הַלֵּב, הַגַּעְגּוּעַ וְהַשִּׁיבָה ──────────────
  {
    id: 'p-tehilim-42-2',
    he: 'כְּאַיָּל תַּעֲרֹג עַל אֲפִיקֵי מָיִם כֵּן נַפְשִׁי תַעֲרֹג אֵלֶיךָ אֱלֹהִים',
    es: 'Como el ciervo brama por las corrientes de agua, así mi alma clama por Ti, Elokim.',
    source: 'תְּהִלִּים מ״ב:ב׳',
    sourceEs: 'Tehilim 42:2',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-63-2',
    he: 'אֱלֹהִים אֵלִי אַתָּה אֲשַׁחֲרֶךָּ צָמְאָה לְךָ נַפְשִׁי כָּמַהּ לְךָ בְשָׂרִי',
    es: 'Dios, Tú eres mi Dios, te busco al alba; mi alma tiene sed de Ti, mi carne entera te anhela.',
    source: 'תְּהִלִּים ס״ג:ב׳',
    sourceEs: 'Tehilim 63:2',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-27-8',
    he: 'לְךָ אָמַר לִבִּי בַּקְּשׁוּ פָנָי אֶת פָּנֶיךָ ה׳ אֲבַקֵּשׁ',
    es: 'A Ti dijo mi corazón: «Busquen Mi rostro»; Tu rostro, Hashem, es lo que busco.',
    source: 'תְּהִלִּים כ״ז:ח׳',
    sourceEs: 'Tehilim 27:8',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-73-26',
    he: 'כָּלָה שְׁאֵרִי וּלְבָבִי צוּר לְבָבִי וְחֶלְקִי אֱלֹהִים לְעוֹלָם',
    es: 'Mi carne y mi corazón se consumen; la roca de mi corazón y mi porción es Dios, para siempre.',
    source: 'תְּהִלִּים ע״ג:כ״ו',
    sourceEs: 'Tehilim 73:26',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'p-tehilim-84-3',
    he: 'נִכְסְפָה וְגַם כָּלְתָה נַפְשִׁי לְחַצְרוֹת ה׳ לִבִּי וּבְשָׂרִי יְרַנְּנוּ אֶל אֵל חָי',
    es: 'Anhela y hasta desfallece mi alma por los atrios de Hashem; mi corazón y mi carne cantan al Dios vivo.',
    source: 'תְּהִלִּים פ״ד:ג׳',
    sourceEs: 'Tehilim 84:3',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-shir-6-3',
    he: 'אֲנִי לְדוֹדִי וְדוֹדִי לִי הָרוֹעֶה בַּשּׁוֹשַׁנִּים',
    es: 'Yo soy de mi Amado y mi Amado es mío.',
    source: 'שִׁיר הַשִּׁירִים ו׳:ג׳',
    sourceEs: 'Shir HaShirim 6:3 (א־ל־ו־ל)',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-devarim-6-5',
    he: 'וְאָהַבְתָּ אֵת ה׳ אֱלֹהֶיךָ בְּכָל לְבָבְךָ וּבְכָל נַפְשְׁךָ וּבְכָל מְאֹדֶךָ',
    es: 'Y amarás a Hashem tu Dios con todo tu corazón, con toda tu alma y con todo lo que tienes.',
    source: 'דְּבָרִים ו׳:ה׳',
    sourceEs: 'Devarim 6:5',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'p-tehilim-86-11',
    he: 'הוֹרֵנִי ה׳ דַּרְכֶּךָ אֲהַלֵּךְ בַּאֲמִתֶּךָ יַחֵד לְבָבִי לְיִרְאָה שְׁמֶךָ',
    es: 'Enséñame, Hashem, Tu camino; unifica mi corazón para temer Tu nombre.',
    source: 'תְּהִלִּים פ״ו:י״א',
    sourceEs: 'Tehilim 86:11',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'p-tehilim-116-1',
    he: 'אָהַבְתִּי כִּי יִשְׁמַע ה׳ אֶת קוֹלִי תַּחֲנוּנָי',
    es: 'Amo a Hashem, porque escucha mi voz, mis súplicas.',
    source: 'תְּהִלִּים קט״ז:א׳',
    sourceEs: 'Tehilim 116:1',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-145-18',
    he: 'קָרוֹב ה׳ לְכָל קֹרְאָיו לְכֹל אֲשֶׁר יִקְרָאֻהוּ בֶאֱמֶת',
    es: 'Cercano está Hashem a todos los que lo llaman, a todos los que lo llaman de verdad.',
    source: 'תְּהִלִּים קמ״ה:י״ח',
    sourceEs: 'Tehilim 145:18',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-51-19',
    he: 'זִבְחֵי אֱלֹהִים רוּחַ נִשְׁבָּרָה לֵב נִשְׁבָּר וְנִדְכֶּה אֱלֹהִים לֹא תִבְזֶה',
    es: 'Los sacrificios de Dios son un espíritu quebrado; un corazón roto y contrito, Elokim, no lo desprecias.',
    source: 'תְּהִלִּים נ״א:י״ט',
    sourceEs: 'Tehilim 51:19',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-51-12',
    he: 'לֵב טָהוֹר בְּרָא לִי אֱלֹהִים וְרוּחַ נָכוֹן חַדֵּשׁ בְּקִרְבִּי',
    es: 'Un corazón puro créame, Dios, y un espíritu firme renueva dentro de mí.',
    source: 'תְּהִלִּים נ״א:י״ב',
    sourceEs: 'Tehilim 51:12',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-34-19',
    he: 'קָרוֹב ה׳ לְנִשְׁבְּרֵי לֵב וְאֶת דַּכְּאֵי רוּחַ יוֹשִׁיעַ',
    es: 'Cercano está Hashem a los quebrados de corazón, y salva a los de espíritu abatido.',
    source: 'תְּהִלִּים ל״ד:י״ט',
    sourceEs: 'Tehilim 34:19',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-130-1',
    he: 'מִמַּעֲמַקִּים קְרָאתִיךָ ה׳',
    es: 'Desde lo más hondo te llamé, Hashem.',
    source: 'תְּהִלִּים ק״ל:א׳',
    sourceEs: 'Tehilim 130:1',
    theme: 'teshuva',
    tone: 'firm',
  },
  {
    id: 'p-tehilim-62-9',
    he: 'בִּטְחוּ בוֹ בְכָל עֵת עָם שִׁפְכוּ לְפָנָיו לְבַבְכֶם',
    es: 'Confíen en Él en todo momento; derramen ante Él su corazón.',
    source: 'תְּהִלִּים ס״ב:ט׳',
    sourceEs: 'Tehilim 62:9',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'p-tehilim-30-6',
    he: 'בָּעֶרֶב יָלִין בֶּכִי וְלַבֹּקֶר רִנָּה',
    es: 'Al anochecer se aloja el llanto, y a la mañana, el canto.',
    source: 'תְּהִלִּים ל׳:ו׳',
    sourceEs: 'Tehilim 30:6',
    theme: 'simja',
    tone: 'gentle',
  },
  {
    id: 'p-eicha-3-23',
    he: 'חֲדָשִׁים לַבְּקָרִים רַבָּה אֱמוּנָתֶךָ',
    es: 'Nuevas cada mañana; grande es Tu fidelidad.',
    source: 'אֵיכָה ג׳:כ״ג',
    sourceEs: 'Eijá 3:23',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'p-hoshea-14-2',
    he: 'שׁוּבָה יִשְׂרָאֵל עַד ה׳ אֱלֹהֶיךָ כִּי כָשַׁלְתָּ בַּעֲוֺנֶךָ',
    es: 'Vuelve, Israel, hasta Hashem tu Dios, porque tropezaste en tu falta.',
    source: 'הוֹשֵׁעַ י״ד:ב׳',
    sourceEs: 'Hoshea 14:2 (haftará de Shabat Shuvá)',
    theme: 'teshuva',
    tone: 'firm',
  },
  {
    id: 'p-yeshaya-55-6',
    he: 'דִּרְשׁוּ ה׳ בְּהִמָּצְאוֹ קְרָאֻהוּ בִּהְיוֹתוֹ קָרוֹב',
    es: 'Busquen a Hashem mientras se deja hallar, llámenlo mientras está cerca.',
    source: 'יְשַׁעְיָהוּ נ״ה:ו׳',
    sourceEs: 'Yeshayahu 55:6',
    theme: 'teshuva',
    tone: 'demanding',
  },
  {
    id: 'p-yirmiya-29-13',
    he: 'וּבִקַּשְׁתֶּם אֹתִי וּמְצָאתֶם כִּי תִדְרְשֻׁנִי בְּכָל לְבַבְכֶם',
    es: 'Me buscarán y me encontrarán, cuando me busquen con todo el corazón.',
    source: 'יִרְמְיָהוּ כ״ט:י״ג',
    sourceEs: 'Yirmiyahu 29:13',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'p-yoel-2-13',
    he: 'וְקִרְעוּ לְבַבְכֶם וְאַל בִּגְדֵיכֶם וְשׁוּבוּ אֶל ה׳ אֱלֹהֵיכֶם',
    es: 'Rasguen su corazón y no sus vestiduras, y vuelvan a Hashem su Dios.',
    source: 'יוֹאֵל ב׳:י״ג',
    sourceEs: 'Yoel 2:13',
    theme: 'teshuva',
    tone: 'demanding',
  },
  {
    id: 'p-amos-4-12',
    he: 'הִכּוֹן לִקְרַאת אֱלֹהֶיךָ יִשְׂרָאֵל',
    es: 'Prepárate para encontrarte con tu Dios, Israel.',
    source: 'עָמוֹס ד׳:י״ב',
    sourceEs: 'Amós 4:12',
    theme: 'zman',
    tone: 'demanding',
  },
  {
    id: 'p-mishle-27-1',
    he: 'אַל תִּתְהַלֵּל בְּיוֹם מָחָר כִּי לֹא תֵדַע מַה יֵּלֶד יוֹם',
    es: 'No te jactes del día de mañana, porque no sabes qué habrá de parir el día.',
    source: 'מִשְׁלֵי כ״ז:א׳',
    sourceEs: 'Mishlé 27:1',
    theme: 'zman',
    tone: 'demanding',
  },
  {
    id: 'p-kohelet-9-10',
    he: 'כֹּל אֲשֶׁר תִּמְצָא יָדְךָ לַעֲשׂוֹת בְּכֹחֲךָ עֲשֵׂה',
    es: 'Todo lo que tu mano encuentre para hacer, hazlo con toda tu fuerza.',
    source: 'קֹהֶלֶת ט׳:י׳',
    sourceEs: 'Kohelet 9:10',
    theme: 'exigencia',
    tone: 'demanding',
  },
  {
    id: 'p-kohelet-12-1',
    he: 'וּזְכֹר אֶת בּוֹרְאֶיךָ בִּימֵי בְּחוּרֹתֶיךָ',
    es: 'Recuerda a tu Creador en los días de tu juventud, antes de que lleguen los días malos.',
    source: 'קֹהֶלֶת י״ב:א׳',
    sourceEs: 'Kohelet 12:1',
    theme: 'zman',
    tone: 'firm',
  },
  {
    id: 'g-berachot-28b-lifnei',
    he: 'דְּעוּ לִפְנֵי מִי אַתֶּם עוֹמְדִים לִפְנֵי מֶלֶךְ מַלְכֵי הַמְּלָכִים',
    es: 'Cuando reces, sabe ante Quién estás de pie: ante el Rey de todos los reyes.',
    source: 'בְּרָכוֹת כ״ח:',
    sourceEs: 'Berajot 28b',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'a-2-10-teshuva',
    he: 'וְשׁוּב יוֹם אֶחָד לִפְנֵי מִיתָתְךָ',
    es: 'Vuelve un día antes de tu muerte — y como no sabes cuándo será, vuelve hoy.',
    source: 'אָבוֹת ב׳:י׳',
    sourceEs: 'Pirkei Avot 2:10 (Rabí Eliezer); Shabat 153a',
    theme: 'teshuva',
    tone: 'demanding',
  },

  // ────────── ספרי מוסר — אַהֲבָה, בְּכִיָּה וּתְשׁוּבָה מִן הַלֵּב ──────────
  {
    id: 'm-chovot-ahava',
    es: 'Amar a Hashem es que no quede en el alma ni un rincón ocupado por otra cosa que no sea Él.',
    source: 'חוֹבוֹת הַלְּבָבוֹת, שַׁעַר אַהֲבַת ה׳',
    sourceEs: 'Jovot HaLevavot, Portal del Amor a Hashem',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'm-chovot-bechina',
    es: 'Mira el cielo, mira tu propio cuerpo, mira el pan que vas a comer: todo te está diciendo, ahora mismo, que hay Alguien que te sostiene.',
    source: 'חוֹבוֹת הַלְּבָבוֹת, שַׁעַר הַבְּחִינָה',
    sourceEs: 'Jovot HaLevavot, Portal de la Reflexión',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'm-rambam-teshuva-10-3',
    es: '¿Cómo es el amor debido? Amar a Hashem tanto que el alma quede atada a ese amor, como el que está enfermo de amor y no piensa en otra cosa.',
    source: 'רַמְבַּ״ם, הִלְכוֹת תְּשׁוּבָה י׳:ג׳',
    sourceEs: 'Rambam, Hiljot Teshuvá 10:3',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'm-rambam-teshuva-7-7',
    es: 'Qué grande es la teshuvá: ayer esta persona estaba lejana y odiada; hoy, después de volver, está amada, cercana y deseada.',
    source: 'רַמְבַּ״ם, הִלְכוֹת תְּשׁוּבָה ז׳:ו׳-ז׳',
    sourceEs: 'Rambam, Hiljot Teshuvá 7:6–7',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'm-nachman-hitbodedut',
    es: 'Háblale a Hashem con tus propias palabras, en tu idioma, como un hijo que se desahoga con su padre. Eso solo ya te cambia el día.',
    source: 'לִקּוּטֵי מוֹהֲרַ״ן — הִתְבּוֹדְדוּת',
    sourceEs: 'Rabí Najman de Breslov, sobre la hitbodedut',
    theme: 'prioridad',
    tone: 'gentle',
  },
  {
    id: 'm-nachman-simcha-grieta',
    es: 'Ninguna caída es tan honda como para que la alegría no pueda entrar por una grieta. Buscá esa grieta.',
    source: 'ר׳ נַחְמָן מִבְּרֶסְלֶב',
    sourceEs: 'Rabí Najman de Breslov',
    theme: 'simja',
    tone: 'gentle',
  },
  {
    id: 'm-besht-tzilcha',
    es: 'Hashem es tu sombra: en la medida en que te acercas tú, se acerca Él.',
    source: 'הַבַּעַל שֵׁם טוֹב, עַל "ה׳ צִלְּךָ"',
    sourceEs: 'El Baal Shem Tov, sobre «Hashem es tu sombra» (Tehilim 121:5)',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'm-kook-orot-teshuva',
    es: 'El deseo de volver a la raíz nunca se apaga del todo; sigue encendido bajo las cenizas, esperando que soples.',
    source: 'אוֹרוֹת הַתְּשׁוּבָה',
    sourceEs: 'Rav A. I. HaKohen Kook, Orot HaTeshuvá',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'm-sfat-emet-nekuda',
    es: 'Dentro de cada judío hay un punto en el corazón que nunca se ensució. Toda la avodá es volver a descubrirlo.',
    source: 'שְׂפַת אֱמֶת',
    sourceEs: 'Sfat Emet (Rebe de Gur)',
    theme: 'teshuva',
    tone: 'gentle',
  },
  {
    id: 'm-mesilat-ahava',
    es: 'El corazón tiene que arder por acercarse a Él como arde el que ama y no encuentra descanso lejos de su amada.',
    source: 'מְסִלַּת יְשָׁרִים י״ט',
    sourceEs: 'Mesilat Yesharim, cap. 19 (el amor a Hashem)',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'm-derech-hashem-tachlit',
    es: 'El propósito de toda la creación se juega en algo pequeño: que tú, hoy, elijas acercarte a Él.',
    source: 'דֶּרֶךְ ה׳, חֵלֶק א׳',
    sourceEs: 'Derekh Hashem, parte 1 (Ramjal)',
    theme: 'prioridad',
    tone: 'firm',
  },
  {
    id: 'm-chofetz-chaim-vela',
    es: 'Un poco de luz expulsa mucha oscuridad. No midas tu vela por lo negra que esté la noche afuera.',
    source: 'הֶחָפֵץ חַיִּים',
    sourceEs: 'El Jafétz Jaim',
    theme: 'simja',
    tone: 'gentle',
  },
  {
    id: 'm-slabodka-gadlut',
    es: 'Acuérdate de Quién eres hijo. Te sale barato rebajarte solo porque olvidaste tu linaje.',
    source: 'הַסַּבָּא מִסְלַבּוֹדְקָא — גַּדְלוּת הָאָדָם',
    sourceEs: 'El Alter de Slabodka — gadlut haadam',
    theme: 'anava',
    tone: 'firm',
  },
  {
    id: 'm-salanter-mida',
    es: 'Cambiar una sola midá es más difícil que partir el mar; por eso vale gastar una vida entera en el intento.',
    source: 'ר׳ יִשְׂרָאֵל סָלַנְטֶר',
    sourceEs: 'Rabí Israel Salanter',
    theme: 'exigencia',
    tone: 'firm',
  },
  {
    id: 'm-yona-charata',
    es: 'La teshuvá empieza el instante en que el corazón se duele de verdad por haberse alejado. Ese dolor no es castigo: es la puerta.',
    source: 'שַׁעֲרֵי תְּשׁוּבָה, שַׁעַר א׳',
    sourceEs: 'Shaarei Teshuvá, Portal 1 (Rabenu Yoná)',
    theme: 'teshuva',
    tone: 'firm',
  },
];

export const MUSAR_BY_ID: Record<string, MusarLine> = Object.fromEntries(MUSAR.map((l) => [l.id, l]));
